[package]
name = "zen"
version = "0.1.0"
authors = ["Pocket7878 <poketo7878@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zenhub-api = { path = "../zenhub-api" }
tokio = "0.2"
clap = "2.33.0"